# Permalinks
permalink:           pretty

# Setup
title:               Kushal Arora
url:                 http://kushalarora.github.io
paginate:            5
baseurl:             ""
paginate_path: '/blog/page:num'
analytics_id: 'UA-87687456-1'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Kushal Arora
  url:               https://kushalarora.github.io
  email:             kushal18@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Pagelist
pages_list:
    Misc.: '/misc'
    Updates: '/updates'
#    Blog: '/blog'


# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
